apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivapp1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivapp1
  template:
    metadata:
      labels:
        app: trivapp1
    spec:
      containers:
      - name: app1
        image: asia-south1-docker.pkg.dev/triv-case/triv-repo/trivapp1:latest
        ports:
        - containerPort: 8080