apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivapp1-deployment
  namespace: trivapp-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivapp1
  template:
    metadata:
      labels:
        app: trivapp1
    spec:
      containers:
      - image: asia-south1-docker.pkg.dev/triv-case/triv-repo/trivapp1:latest
        name: app1
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      securityContext:
        allowPrivilegeEscalation: false
        fsGroup: 2000
        readOnlyRootFilesystem: true
        runAsGroup: 3000
        runAsNonRoot: true
        runAsUser: 1000
